### ISSUE TITLE
feat: Manually show ui without having to shake

### ISSUE THREAD

**Issue by kuyazee** [bayunugroho2022/dio-request-inspector#31]
**Description**

Ability to show the request inspector by calling a function

**Sample Pseudocode**

```dart
DioRequestInspector.show(context);

or

DioRequestInspector.show();
```

**Comment by bayunugroho2022** [comment]
Thank you for your input.

I appreciate your suggestion to add the ability to display inspector requests by calling the `DioRequestInspector.show(context)` or `DioRequestInspector.show()` functions. I will endeavor to incorporate this feedback into the next version release.

**Comment by bayunugroho2022** [comment]
in version 3.1.0 you can using
```dart
inspector.toInspector
```

full example : https://github.com/bayunugroho2022/dio-request-inspector/blob/master/example/lib/main.dart

this problem is solved with this PR https://github.com/bayunugroho2022/dio-request-inspector/pull/32
